// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDO8kdJSlT-nqXw69YXqwvzzJI7dItGQDk',
    appId: '1:1034460062982:web:22eb181c41f647ef8f6a87',
    messagingSenderId: '1034460062982',
    projectId: 'api-integration-5fdba',
    authDomain: 'api-integration-5fdba.firebaseapp.com',
    storageBucket: 'api-integration-5fdba.appspot.com',
    measurementId: 'G-T885C39XG9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKft26gieVwrCfMLnETsPYSFDItjYZ3vQ',
    appId: '1:1034460062982:android:86814d36d74ff4908f6a87',
    messagingSenderId: '1034460062982',
    projectId: 'api-integration-5fdba',
    storageBucket: 'api-integration-5fdba.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6i0-mFG9A1-ee99xNLu28CCn9CPiCv1c',
    appId: '1:1034460062982:ios:4dfb6c44856c6ac98f6a87',
    messagingSenderId: '1034460062982',
    projectId: 'api-integration-5fdba',
    storageBucket: 'api-integration-5fdba.appspot.com',
    iosBundleId: 'com.example.flutterApi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6i0-mFG9A1-ee99xNLu28CCn9CPiCv1c',
    appId: '1:1034460062982:ios:1af3dc4018fe024f8f6a87',
    messagingSenderId: '1034460062982',
    projectId: 'api-integration-5fdba',
    storageBucket: 'api-integration-5fdba.appspot.com',
    iosBundleId: 'com.example.flutterApi.RunnerTests',
  );
}
